### ISSUE TITLE
Console detach

### ISSUE THREAD

**Issue by userid0x0** [lkvm/lkvm#1]
Hi,
may be a simple question.
I setup a VM using
```
  lkvm setup guest
  lkvm run -d guest -k Image
```
I found that `CTRL+a, x` closes the running KVM guest. Is there a way that I can connect/disconnect from a guest console?
In my setup the current console remains in the guest session till I close the machine.

**Comment by ghost** [comment]
Try with [byobu](https://www.byobu.org/) or [tmux](https://en.wikipedia.org/wiki/Tmux) or [GNU Screen](https://www.gnu.org/software/screen/) as they can "console detach" as you put it.

Also this project has been unmaintained since 2015 and may have vulnerabilities.

**Comment by userid0x0** [comment]
This was my workaround already.

> Also this project has been unmaintained since 2015 and may have vulnerabilities.
Don't mind. I am using lkvm only for research how kvm works.
